# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_entry_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
