# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20170105_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='tag',
            field=models.CharField(default='contacts', max_length=200),
            preserve_default=False,
        ),
    ]
