# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_entry_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='tag',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
