# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_auto_20170106_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='tag',
        ),
    ]
