# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_remove_entry_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Journal'),
        ),
    ]
