# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_journal_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='uuid',
            field=models.UUIDField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='uuid',
            field=models.UUIDField(db_index=True, unique=True),
        ),
    ]
