# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 13:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_auto_20170108_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='uuid',
        ),
        migrations.AddField(
            model_name='entry',
            name='uid',
            field=models.CharField(db_index=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator(message='Not a sha256 value.', regex='[a-fA-F0-9]{64}')]),
        ),
        migrations.AddField(
            model_name='journal',
            name='uid',
            field=models.CharField(db_index=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator(message='Not a sha256 value.', regex='[a-fA-F0-9]{64}')]),
        ),
    ]
