# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 14:00
from __future__ import unicode_literals

import hashlib

from django.db import migrations


def gen_uid(apps, schema_editor):
    Journal = apps.get_model('journal', 'Journal')
    Entry = apps.get_model('journal', 'Entry')
    for row in Journal.objects.all():
        row.uid = hashlib.sha256(row.content).hexdigest()
        row.save()
        prev_hash = ""
        for entry in Entry.objects.filter(journal__pk=row.pk):
            entry.uid = hashlib.sha256(prev_hash.encode('utf-8') +
                                       entry.content).hexdigest()
            prev_hash = entry.uid
            entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_auto_20170110_1359'),
    ]

    operations = [
        migrations.RunPython(gen_uid, reverse_code=migrations.RunPython.noop),
    ]
