# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 14:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_populate_uid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='uid',
            field=models.CharField(db_index=True, max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Not a sha256 value.', regex='[a-fA-F0-9]{64}')]),
        ),
        migrations.AlterField(
            model_name='journal',
            name='uid',
            field=models.CharField(db_index=True, max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Not a sha256 value.', regex='[a-fA-F0-9]{64}')]),
        ),
    ]
