# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 17:37
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0015_remove_uid_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='uid',
            field=models.CharField(db_index=True, max_length=64, validators=[django.core.validators.RegexValidator(message='Not a sha256 value.', regex='[a-fA-F0-9]{64}')]),
        ),
        migrations.AlterField(
            model_name='journal',
            name='uid',
            field=models.CharField(db_index=True, max_length=64, validators=[django.core.validators.RegexValidator(message='Not a sha256 value.', regex='[a-fA-F0-9]{64}')]),
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('uid', 'journal')]),
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together=set([('uid', 'owner')]),
        ),
    ]
